### ISSUE TITLE
AWS::Route53Resolver::ResolverRule has incorrect example

### ISSUE THREAD

**Issue by jmkgreen** [awsdocs/aws-cloudformation-user-guide#335] opened 2019-05-13 16:24 UTC
Under Properties is TargetIps which is not documented correctly.

It requires both `Ip` (lowercase p) and a `Port`, such as:

```
      TargetIps :
        -
          Ip : 192.168.200.1
          Port: "53"
```

**Comment by JohannesKonings** [comment] 2020-01-14 19:32
in german it's still the wrong example: https://docs.aws.amazon.com/de_de/AWSCloudFormation/latest/UserGuide/aws-resource-route53resolver-resolverrule.html

`Type : AWS::Route53Resolver::ResolverRule
Properties : 
  DomainName : example.com
  Name : MyRule
  ResolverEndpointId : rslvr-out-fdc049932dexample
  RuleType : FORWARD 
  Tags : 
    - 
      Key : LineOfBusiness
      Value : Engineering
  TargetIps :
    - 
      IP : 192.0.2.6
      IP : 192.0.2.99`

**Comment by rachfop** [comment] 2020-05-27 16:02
Hello, thank you for your suggestions. It seems that the issue is now fixed: (German): https://docs.aws.amazon.com/de_de/AWSCloudFormation/latest/UserGuide/aws-resource-route53resolver-resolverrule.html

and (English): https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53resolver-resolverrule.html

  TargetIps :
    - 
      Ip : 192.0.2.6
      Port : 53
    -  
      Ip : 192.0.2.99
      Port : 53

**Closed by rachfop** 2020-05-27 16:02 UTC
