### ISSUE TITLE
S3 Bucket Pages are not working and redirect to homepage

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-cloudformation-user-guide#1141] opened 2022-01-28 20:59 UTC
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html doesn't work for the high level S3 Bucket CloudFormation Page and will redirect to the CloudFormation homepage: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html. 

Some of the child pages still work: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-publicaccessblockconfiguration.html

**Comment by rachfop** [comment] 2022-01-31 02:59
I have pushed a fix for this. Can you try again and close the issue if it is fixed for you as well?

Thanks!

**Comment by rachfop** [comment] 2022-01-31 16:26
Duplicate of  https://github.com/awsdocs/aws-cloudformation-user-guide/issues/1140. Closing. 

Thank you for identifying this!

**Closed by rachfop** 2022-01-31 16:26 UTC
